name: "Test changed lines"
on:  
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@ff5487344fef179bdd067ed995d0c407a2967b99
      - name: Print changed lines
        run: echo ${{ steps.changed_lines.outputs.changed_lines }}